# lightning.pytorch==2.2.0
seed_everything: 0
#ckpt_path: /home/bosheng/deepfake-detect-main/lightning_logs/version_152/checkpoints/epoch=3-step=3720.ckpt
model:
  class_path: trainer.deepfake_detect.DetectModule
  init_args:
    optimizer_args:
      lr: 2e-6
      lr_backbone: 1e-4
      lr_clr: 1e-3
      lr_weight_decay: 1e-4
    num_queries: 8
    num_classes: 2
    cropped_size: 12
    freeze_encoder: False
    freeze_decoder: False
    extracted_layer: self.model.model.backbone.conv_encoder.model.layer1[0].conv3
    optimizer: AdamW
    overlap_loss_weight: 2
data:
  class_path: dataset.data_modules.NTObjectDataModule
  init_args:
    root_dir: /data/Deepfake/celeb_object
#    root_dir2: /data/Deepfake/NT_object  ff_c23_object celeb_object
    batch_size: 192
    num_workers: 32
    image_size: 256
trainer:
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:  # minimal val_loss checkpoint
        every_n_epochs: 1
        save_top_k: 1
        monitor: val_gnn_loss
        mode: min
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:  # maximum val_acc1 checkpoint
        every_n_epochs: 1
        save_top_k: 1
        monitor: val_acc1
        mode: max
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args: # maximum val_auc1 checkpoint
        every_n_epochs: 1
        save_top_k: 1
        monitor: val_auc1
        mode: max
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 1
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: 3
  enable_progress_bar: True
  precision: 32-true #16-mixed 32-true
  max_epochs: 50
#  logger: False
